# Generated by Django 2.0 on 2019-03-20 21:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('crud_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation, update, delete.. date')),
                ('payload', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('description', models.TextField()),
                ('creation', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=10)),
                ('payload', models.CharField(max_length=200)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Categorie')),
                ('like', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forum.Like')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('login', models.CharField(max_length=45)),
                ('passwd', models.CharField(max_length=45)),
                ('inscription_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('photo', models.CharField(max_length=200)),
                ('like', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forum.Like')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Post'),
        ),
    ]
