# Generated by Django 2.0 on 2019-03-22 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='names',
            new_name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(default=django.utils.timezone.now, max_length=45),
            preserve_default=False,
        ),
    ]
