# Generated by Django 2.1.7 on 2019-03-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20190322_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['crud_date'], 'verbose_name': 'un commentaire'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['creation'], 'verbose_name': 'un poste'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='payload',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='payload',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
