# Generated by Django 2.1.7 on 2019-03-24 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190324_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['creation_date'], 'verbose_name': 'un poste'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='creation',
        ),
        migrations.AddField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de creation du poste'),
        ),
    ]
