# Generated by Django 2.1.7 on 2019-03-24 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_auto_20190324_1331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['crud_date'], 'verbose_name': 'un poste'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='post',
            name='crud_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation, update, delete.. date'),
        ),
    ]
