# Generated by Django 2.1.7 on 2019-03-24 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_auto_20190324_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.RemoveField(
            model_name='user',
            name='like',
        ),
        migrations.AddField(
            model_name='like',
            name='poste',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.Post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='forum.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Categorie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
