# Generated by Django 2.1.7 on 2019-03-24 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20190324_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='com',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Comment'),
        ),
    ]
