# Generated by Django 2.0 on 2019-04-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20190409_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(max_length=200, null=True, upload_to=''),
        ),
    ]
