# Generated by Django 2.2 on 2019-04-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='comment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
