# Generated by Django 2.2 on 2019-04-11 05:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0013_commentaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('crud_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation, update, delete.. date')),
                ('payload', models.CharField(max_length=45, null=True)),
                ('com', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Comment')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.User')),
            ],
            options={
                'verbose_name': 'un commentaire',
                'ordering': ['crud_date'],
            },
        ),
        migrations.DeleteModel(
            name='Commentaire',
        ),
    ]
